export default {
  backGround: '#fff',
  backGroundBtnInactive: '#9D9D9D',
  backGroundTabThuChi: '#EFEFEF',
  backGroundBtnActive: 'green',
  backGroundHeader: 'green',
  boderColor: '#000',
  colorText: '#000',
  colorTextBtn: '#fff',
  colorTextDK: 'green',
  placeholder: '#9D9D9D',
  colorLine: '#9D9D9D',
  colorDateActive: 'blue',
  backGroundBtnKhoanChi: 'red',
  backGroundBtnKhoanThu: 'green',
  error: 'red',
  succcess: 'green',
};
